export enum ContactDetailActionEnum {
  FETCH_CONTACT_DETAIL_REQUEST = "FETCH_CONTACT_DETAIL_REQUEST",
  FETCH_CONTACT_DETAIL_SUCCESS = "FETCH_CONTACT_DETAIL_SUCCESS",
  FETCH_CONTACT_DETAIL_FAILURE = "FETCH_CONTACT_DETAIL_FAILURE",
}

export default ContactDetailActionEnum;
