export enum ContactActionEnum {
  FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST",
  FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS",
  FETCH_CONTACT_FAILURE = "FETCH_CONTACT_FAILURE",

  FETCH_CONTACT_DETAIL_REQUEST = "FETCH_CONTACT_DETAIL_REQUEST",
  FETCH_CONTACT_DETAIL_SUCCESS = "FETCH_CONTACT_DETAIL_SUCCESS",
  FETCH_CONTACT_DETAIL_FAILURE = "FETCH_CONTACT_DETAIL_FAILURE",

  DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST",
  DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE",
}

export default ContactActionEnum;
