export enum ContactActionEnum {
  FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST",
  FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS",
  FETCH_CONTACT_FAILURE = "FETCH_CONTACT_FAILURE",
}

export default ContactActionEnum;
